language: java
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: GU8mImUCPz7ChQqwb/JuWwIM6k+1VB5VWZmKPA+4n98qYkNqPj4ZBii4e8Iv5NUX1J5Fh61ha/BocSj9XkgScODLEZVsQu3YPCDwumcM9nVV4GFNG9u8pIaJ+1NnL5OowrSYfRcXFum3kXJO9uP4ZSRiSG2TRnMMVmXSJKzYPZc=
  - secure: VcexGNDJ+67Kv2M9+81msyp7Ne9TuaTXwUYMa428AGqLFgP17BxQXTVaGTqNxyXAvSg4SLYGJN41lOCmW+jPGjOFFjKjeyK5TCtdBIsB/NsMWnA3SCkQK3/O9TNVr2GerayUoGBFrmKCh9Qc6TtzZu5SerlGFsMFFYhDE4rkZ2U=
